name: CI

on:
    push:
        branches:
            - master
            - release/*

jobs:
    firebase-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: "12.x"
            - name: Build
              run: npm ci && npm run build
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting:production-site
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  VUE_APP_IMAGE_COLLECTION: "images"
