name: CI

on:
    push:
        branches:
            - develop
            - test-deploy

jobs:
    firebase-deploy-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: "12.x"
            - name: Build
              run: npm ci && npm run build -- --mode development
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting:development-site
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
